[postgres]
host = "kutone.khoraurbanthinkers.es"
port = 5432
dbname = "Khora_base_datos"
user = "juan"
password = "QzXDkZF9WNHg9qr68lG0U695Q"
db_url = "postgresql://juan:QzXDkZF9WNHg9qr68lG0U695Q@192.168.1.151:5432/Khora_base_datos"